DEBUG 2017-12-06 10:13:29,201: 	 Executing command: 'status'
DEBUG 2017-12-06 10:13:29,202: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2017-12-06 10:13:29,219: 	 Checking credentials
DEBUG 2017-12-06 10:13:29,219: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2017-12-06 10:13:29,219: 	 Getting proxy life time left
DEBUG 2017-12-06 10:13:29,322: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 81831

 error: 
 retcode : 0
DEBUG 2017-12-06 10:13:29,426: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 81831

 error: 
 retcode : 0
DEBUG 2017-12-06 10:13:29,426: 	 Proxy valid for 22:43:51 hours
ERROR 2017-12-06 10:13:29,427: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/samuellh/WorkingArea/TauAnalysis/CMSSW_9_3_2/src/PUAnalysis/VBFtt2017/crab/VBF1/2017MC_VBFtt
ERROR 2017-12-06 10:13:29,427: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/samuellh/WorkingArea/TauAnalysis/CMSSW_9_3_2/src/PUAnalysis/VBFtt2017/crab/VBF1/2017MC_VBFtt
DEBUG 2017-12-07 06:14:16,112: 	 Executing command: 'status'
DEBUG 2017-12-07 06:14:16,113: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
ERROR 2017-12-07 06:14:16,122: 	 Error: VBF2/2017MC_VBFtt/crab_20171206_094517/crab.log is not a valid CRAB project directory.
ERROR 2017-12-07 06:14:16,122: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 878, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: VBF2/2017MC_VBFtt/crab_20171206_094517/crab.log is not a valid CRAB project directory.
DEBUG 2017-12-07 07:39:24,227: 	 Executing command: 'status'
DEBUG 2017-12-07 07:39:24,228: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2017-12-07 07:39:24,237: 	 Checking credentials
DEBUG 2017-12-07 07:39:24,238: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2017-12-07 07:39:24,238: 	 Getting proxy life time left
DEBUG 2017-12-07 07:39:24,340: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-12-07 07:39:24,340: 	 Proxy valid for 00:00:00 hours
DEBUG 2017-12-07 07:39:24,340: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2017-12-07 07:59:24,440: 	 Timeout in voms-proxy-init -voms cms:/cms -valid 24:00 -rfc execution.
DEBUG 2017-12-07 07:59:24,646: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-12-07 07:59:24,749: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u52190 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2017-12-07 07:59:24,749: 	 Problems creating proxy.
ERROR 2017-12-07 07:59:24,749: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2018-02-13 14:02:14,078: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:02:14,082: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:02:14,093: 	 Checking credentials
DEBUG 2018-02-13 14:02:14,094: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:02:14,094: 	 Getting proxy life time left
DEBUG 2018-02-13 14:02:14,197: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 43146

 error: 
 retcode : 0
DEBUG 2018-02-13 14:02:14,301: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 43146

 error: 
 retcode : 0
DEBUG 2018-02-13 14:02:14,301: 	 Proxy valid for 11:59:06 hours
INFO 2018-02-13 14:02:14,301: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:02:14,301: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:02:14,552: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:02:14,552: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-13 14:02:59,732: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:02:59,734: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:02:59,744: 	 Checking credentials
DEBUG 2018-02-13 14:02:59,745: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:02:59,745: 	 Getting proxy life time left
DEBUG 2018-02-13 14:02:59,848: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 43101

 error: 
 retcode : 0
DEBUG 2018-02-13 14:02:59,952: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 43101

 error: 
 retcode : 0
DEBUG 2018-02-13 14:02:59,952: 	 Proxy valid for 11:58:21 hours
INFO 2018-02-13 14:02:59,952: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:02:59,953: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:02:59,982: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:02:59,982: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-13 14:03:45,235: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:03:45,236: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:03:45,251: 	 Checking credentials
DEBUG 2018-02-13 14:03:45,251: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:03:45,251: 	 Getting proxy life time left
DEBUG 2018-02-13 14:03:45,355: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 43055

 error: 
 retcode : 0
DEBUG 2018-02-13 14:03:45,459: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 43055

 error: 
 retcode : 0
DEBUG 2018-02-13 14:03:45,460: 	 Proxy valid for 11:57:35 hours
INFO 2018-02-13 14:03:45,463: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:03:45,464: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:03:45,479: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:03:45,479: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-13 14:05:39,681: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:05:39,683: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:05:39,696: 	 Checking credentials
DEBUG 2018-02-13 14:05:39,697: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:05:39,697: 	 Getting proxy life time left
DEBUG 2018-02-13 14:05:39,801: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 42941

 error: 
 retcode : 0
DEBUG 2018-02-13 14:05:39,904: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 42941

 error: 
 retcode : 0
DEBUG 2018-02-13 14:05:39,905: 	 Proxy valid for 11:55:41 hours
INFO 2018-02-13 14:05:39,907: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:05:39,908: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:05:39,949: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:05:39,949: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-13 14:23:51,610: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:23:51,610: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:23:51,623: 	 Checking credentials
DEBUG 2018-02-13 14:23:51,623: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:23:51,623: 	 Getting proxy life time left
DEBUG 2018-02-13 14:23:51,727: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 41849

 error: 
 retcode : 0
DEBUG 2018-02-13 14:23:51,831: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 41849

 error: 
 retcode : 0
DEBUG 2018-02-13 14:23:51,831: 	 Proxy valid for 11:37:29 hours
INFO 2018-02-13 14:23:51,832: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:23:51,832: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:23:51,847: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:23:51,847: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-13 14:24:11,238: 	 Executing command: 'submit'
DEBUG 2018-02-13 14:24:11,239: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2018-02-13 14:24:11,247: 	 Checking credentials
DEBUG 2018-02-13 14:24:11,247: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2018-02-13 14:24:11,247: 	 Getting proxy life time left
DEBUG 2018-02-13 14:24:11,349: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 41829

 error: 
 retcode : 0
DEBUG 2018-02-13 14:24:11,453: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 41829

 error: 
 retcode : 0
DEBUG 2018-02-13 14:24:11,453: 	 Proxy valid for 11:37:09 hours
INFO 2018-02-13 14:24:11,453: 	 Will use CRAB configuration file crab3_cp_mc.py
DEBUG 2018-02-13 14:24:11,454: 	 Loading CRAB configuration file.
ERROR 2018-02-13 14:24:11,463: 	 Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-02-13 14:24:11,464: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'crab'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-02-14 13:01:32,953: 	 Executing command: 'status'
DEBUG 2018-02-14 13:01:32,954: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
ERROR 2018-02-14 13:01:32,957: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/samuellh/WorkingArea/CpHiggs/CMSSW_8_0_21/src/PUAnalysis/VBFtt2017/crab/VBF/2018_MC_VBFtt
ERROR 2018-02-14 13:01:32,957: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 259, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 972, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 577, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1802/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 438, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/samuellh/WorkingArea/CpHiggs/CMSSW_8_0_21/src/PUAnalysis/VBFtt2017/crab/VBF/2018_MC_VBFtt
DEBUG 2018-02-14 16:43:49,282: 	 Executing command: 'status'
DEBUG 2018-02-14 16:43:49,283: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
