DEBUG 2017-11-15 17:38:39,580: 	 Executing command: 'submit'
DEBUG 2017-11-15 17:38:39,580: 	 Found CRAB cache file /uscms/home/samuellh/.crab3
DEBUG 2017-11-15 17:38:39,590: 	 Checking credentials
DEBUG 2017-11-15 17:38:39,590: 	 Found proxy file /tmp/x509up_u52190
DEBUG 2017-11-15 17:38:39,590: 	 Getting proxy life time left
DEBUG 2017-11-15 17:38:39,693: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -timeleft
 output : 37368

 error: 
 retcode : 0
DEBUG 2017-11-15 17:38:39,796: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52190 -actimeleft
 output : 37368

 error: 
 retcode : 0
DEBUG 2017-11-15 17:38:39,797: 	 Proxy valid for 10:22:48 hours
INFO 2017-11-15 17:38:39,797: 	 Will use CRAB configuration file crab3_TT_MC.py
DEBUG 2017-11-15 17:38:39,797: 	 Loading CRAB configuration file.
ERROR 2017-11-15 17:38:39,830: 	 Error while loading CRAB configuration:
name 'Data' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2017-11-15 17:38:39,830: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'Data' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
